api_key: rahasia123
cameras:
  '1': rtsp://admin:STSP2026$@192.168.1.15:554/Streaming/Channels/102
  '2': '0'
  '3': rtsp://admin:STSP2026$@192.168.1.10:554/Streaming/Channels/102
  '4': ''
chat_id: 62895359474947@c.us
confidence: 0.55
cooldown: 30
modbus_baud: 9600
modbus_com: COM1
modbus_enabled: true
modbus_ip: 192.168.1.2
modbus_port: 502
modbus_slave: 1
modbus_type: tcp
plc_coils:
  '1': 0
  '2': 1
  '3': 2
  '4': 3
session: default
telegram_chat_id: '-5191012571'
telegram_enabled: false
telegram_token: 8277840015:AAGpvC3GuhTLFBDVg4MfCnXIKwEg8Z1-2l0
waha_enabled: false
waha_url: http://localhost:3001/api/sendImage
